services:
  - type: web
    name: canidt-first
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_WEBHOOK_URL
        sync: false
      - key: VITE_SENDER_NAME
        value: "L'équipe Candidate First"
