services:
  - type: web
    name: canidt-first
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    headers:
      - path: /assets/*.css
        name: Content-Type
        value: text/css; charset=utf-8
      - path: /assets/*.js
        name: Content-Type
        value: application/javascript; charset=utf-8
    envVars:
      - key: VITE_WEBHOOK_URL
        sync: false
      - key: VITE_SENDER_NAME
        value: "L'équipe Candidate First"
